/*
 * Automatically generated by jrpcgen 1.0.7 on 20.02.16 08:08
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package blinkenbone.rpcgen;
/**
 * A collection of constants used by the "rpc_blinkenlight_api" ONC/RPC program.
 */
public interface rpc_blinkenlight_api {
    public static final int RPC_BLINKENLIGHT_API_MAX_NAME_LEN = 80;
    public static final int RPC_PARAM_CLASS_BUS = 1;
    public static final int RPC_BLINKENLIGHT_API_GETCONTROLINFO_1 = 3;
    public static final int RPC_PARAM_HANDLE_PANEL_MODE = 2;
    public static final int RPC_PARAM_VALUE_PANEL_MODE_POWERLESS = 3;
    public static final int RPC_PARAM_VALUE_PANEL_BLINKENBOARDS_STATE_ACTIVE = 2;
    public static final int RPC_PARAM_VALUE_PANEL_MODE_LAMPTEST = 1;
    public static final int RPC_PARAM_VALUE_PANEL_BLINKENBOARDS_STATE_TRISTATE = 1;
    public static final int RPC_PARAM_VALUE_PANEL_MODE_ALLTEST = 2;
    public static final int RPC_TEST_DATA_TO_SERVER_1 = 1000;
    public static final int RPC_ERR_PARAM_ILL_OBJECT = 2;
    public static final int RPC_BLINKENLIGHT_API_GETPANELINFO_1 = 2;
    public static final int RPC_BLINKENLIGHT_API_MAX_INFOSTRING_LEN = 1024;
    public static final int RPC_PARAM_HANDLE_PANEL_BLINKENBOARDS_STATE = 1;
    public static final int RPC_ERR_PARAM_ILL_PARAM = 3;
    public static final int RPC_PARAM_CLASS_CONTROL = 3;
    public static final int RPC_PARAM_VALUE_PANEL_BLINKENBOARDS_STATE_OFF = 0;
    public static final int RPC_BLINKENLIGHT_API_SETPANEL_CONTROLVALUES_1 = 4;
    public static final int RPC_ERR_PARAM_ILL_CLASS = 1;
    public static final int RPC_PARAM_VALUE_PANEL_MODE_NORMAL = 0;
    public static final int RPC_BLINKENLIGHT_API_GETINFO_1 = 1;
    public static final int RPC_PARAM_CLASS_PANEL = 2;
    public static final int RPC_PARAM_SET_1 = 101;
    public static final int RPC_BLINKENLIGHT_API_GETPANEL_CONTROLVALUES_1 = 5;
    public static final int BLINKENLIGHTD = 99;
    public static final int RPC_TEST_DATA_FROM_SERVER_1 = 1001;
    public static final int RPC_ERR_OK = 0;
    public static final int RPC_PARAM_GET_1 = 100;
    public static final int BLINKENLIGHTD_VERS = 1;
}
// End of rpc_blinkenlight_api.java
