/*
 * Automatically generated by jrpcgen 1.0.7 on 20.02.16 08:08
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package blinkenbone.rpcgen;
/**
 * Enumeration (collection of constants).
 */
public interface rpc_blinkenlight_api_control_type_enum {

    public static final int rpc_blinkenlight_api_input_switch = 1;
    public static final int rpc_blinkenlight_api_output_lamp = 2;

}
// End of rpc_blinkenlight_api_control_type_enum.java
