/*
 * Automatically generated by jrpcgen 1.0.7 on 20.02.16 08:08
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package blinkenbone.rpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class rpc_blinkenlight_api_panel_struct implements XdrAble {
    public rpc_blinkenlight_api_nametype name;
    public int controls_inputs_count;
    public int controls_outputs_count;
    public int controls_inputs_values_bytecount;
    public int controls_outputs_values_bytecount;

    public rpc_blinkenlight_api_panel_struct() {
    }

    public rpc_blinkenlight_api_panel_struct(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        name.xdrEncode(xdr);
        xdr.xdrEncodeInt(controls_inputs_count);
        xdr.xdrEncodeInt(controls_outputs_count);
        xdr.xdrEncodeInt(controls_inputs_values_bytecount);
        xdr.xdrEncodeInt(controls_outputs_values_bytecount);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        name = new rpc_blinkenlight_api_nametype(xdr);
        controls_inputs_count = xdr.xdrDecodeInt();
        controls_outputs_count = xdr.xdrDecodeInt();
        controls_inputs_values_bytecount = xdr.xdrDecodeInt();
        controls_outputs_values_bytecount = xdr.xdrDecodeInt();
    }

}
// End of rpc_blinkenlight_api_panel_struct.java
