/*
 * Automatically generated by jrpcgen 1.0.7 on 20.02.16 08:08
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package blinkenbone.rpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class rpc_blinkenlight_api_control_struct implements XdrAble {
    public rpc_blinkenlight_api_nametype name;
    public byte is_input;
    public rpc_blinkenlight_api_control_type_t type;
    public int radix;
    public int value_bitlen;
    public int value_bytelen;

    public rpc_blinkenlight_api_control_struct() {
    }

    public rpc_blinkenlight_api_control_struct(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        name.xdrEncode(xdr);
        xdr.xdrEncodeByte(is_input);
        type.xdrEncode(xdr);
        xdr.xdrEncodeInt(radix);
        xdr.xdrEncodeInt(value_bitlen);
        xdr.xdrEncodeInt(value_bytelen);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        name = new rpc_blinkenlight_api_nametype(xdr);
        is_input = xdr.xdrDecodeByte();
        type = new rpc_blinkenlight_api_control_type_t(xdr);
        radix = xdr.xdrDecodeInt();
        value_bitlen = xdr.xdrDecodeInt();
        value_bytelen = xdr.xdrDecodeInt();
    }

}
// End of rpc_blinkenlight_api_control_struct.java
