/*
 * Automatically generated by jrpcgen 1.0.7 on 20.02.16 08:08
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package blinkenbone.rpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class rpc_param_cmd_set_struct implements XdrAble {
    public int object_class;
    public int object_handle;
    public int param_handle;
    public int param_value;

    public rpc_param_cmd_set_struct() {
    }

    public rpc_param_cmd_set_struct(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(object_class);
        xdr.xdrEncodeInt(object_handle);
        xdr.xdrEncodeInt(param_handle);
        xdr.xdrEncodeInt(param_value);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        object_class = xdr.xdrDecodeInt();
        object_handle = xdr.xdrDecodeInt();
        param_handle = xdr.xdrDecodeInt();
        param_value = xdr.xdrDecodeInt();
    }

}
// End of rpc_param_cmd_set_struct.java
